name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest  # Specify which runner to use for the deployment job
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy to Amazon Linux Server
      run: |
        # Stop existing application
        ssh -T ec2-user@${{ secrets.SERVER_IP }} "pkill -f 'dotnet.*API.dll'"
    
        # Sync new application files
        rsync -avz --exclude '.git*' --delete ./ ec2-user@${{ secrets.SERVER_IP }}:/home/ec2-user/projects/test/API/bin/Release/net6.0/publish/
    
        # Start the updated application
        ssh -T ec2-user@${{ secrets.SERVER_IP }} "cd /home/ec2-user/projects/test/API/bin/Release/net6.0/publish/ && nohup dotnet API.dll &"
